
server:
  port: 8080
  servlet:
    context-path: /excycle

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-gjwwn326.sql.tencentcdb.com:25290/excycle-3gude89g2e454ced?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: admin
    password: execycle123_
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 60000
      idle-timeout: 600000
      max-lifetime: 1800000

  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

  mvc:
    static-path-pattern: /**

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
    call-setlers-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml

  web:
    resources:
      static-locations:
        - classpath:/static/
      add-mappings: true